import Head from 'next/head';
import { useRouter } from 'next/router';
import en from '../components/Translate/locales/en';
import fr from '../components/Translate/locales/fr';
import Translate from '../components/Translate/Translate';
import styles from '../styles/Home.module.css';

export default function Home() {
  const router = useRouter();
  const { locale } = router;
  const language = locale === 'en' ? en : fr;

  return (
    <>
      <div className={styles.container}>
        <Head>
          <link
            href='https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;500;600&display=swap'
            rel='stylesheet'
          />
          <title>ClimateScience</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <main className={styles.main}>
          <Translate />
          <form className={styles.card}>
            <div className={styles.fade}>
              <h3 className={styles.question}>{language.question}</h3>
              <ul className={styles.choices}>
                <li>
                  <input type='radio' />
                  <label
                    style={{
                      width: '331.16px',
                      height: '49.44px',
                      left: '79.8px',
                      top: ' 0px',
                    }}
                  >
                    {language.option1}
                  </label>
                </li>
                <li>
                  <input type='radio' />
                  <label
                    style={{
                      width: '331.16px',
                      height: '49.44px',
                      left: '79.8px',
                      top: ' 0px',
                    }}
                  >
                    {language.option2}
                  </label>
                </li>
                <li>
                  <input type='radio' defaultChecked />
                  <label
                    style={{
                      width: '331.16px',
                      height: '49.44px',
                      left: '79.8px',
                      top: ' 0px',
                    }}
                  >
                    {language.option3}
                  </label>
                </li>
              </ul>
            </div>
          </form>
        </main>
      </div>
    </>
  );
}
