import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <link
          href='https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;500;600&display=swap'
          rel='stylesheet'
        />
        <title>Question</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <form className={styles.card}>
          <div className={styles.fade}>
            <h3 className={styles.question}>
              Which of the below statements about electricity is not true?
            </h3>
            <ul className={styles.choices}>
              <li>
                <input type='radio' />
                <label
                  style={{
                    width: '331.16px',
                    height: '49.44px',
                    left: '79.8px',
                    top: ' 0px',
                  }}
                >
                  Electricity is measured in units called watts
                </label>
              </li>
              <li>
                <label>
                  <input type='radio' />
                  Electricity flows at the speed of light
                </label>
              </li>
              <li>
                <label>
                  <input type='radio' defaultChecked />
                  Electricity is a primary energy source
                </label>
              </li>
            </ul>
          </div>
        </form>
      </main>
    </div>
  );
}
